name: Crowdin Action

on:
  pull_request:
    branches: [pre-prod]

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: crowdin action
        uses: crowdin/github-action@1.4.9
        with:
          config: 'crowdin.yml'
          download_translations: true
          localization_branch_name: l10n_crowdin_action
          push_translations: true
          commit_message: 'New Crowdin translations by Github Action'
          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: 'pre-prod'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
